-- create table for client meeting -> MEETINGS
CREATE TABLE MEETING(
    meetingId INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId INTEGER,
    meetingTopic VARCHAR(500) NOT NULL,
    meetingDesc VARCHAR(1000) DEFAULT NULL,
    meetingDate TIMESTAMP NOT NULL,
    addedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES USERS(userId)
);